---
name: Build package
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files --ignore-scripts
      - name: Install scripts dependencies
        working-directory: ./scripts
        run: yarn install --frozen-lockfile --check-files --ignore-scripts
      - name: Clean build
        run: rm -rf build plugin/build
      - name: Bake version
        run: yarn bake-version
      - name: Build package
        run: yarn build
      - name: Build up-to-date
        run: git diff --stat --exit-code build
      - name: Build plugin package
        run: yarn build plugin
      - name: Plugin up-to-date
        run: git diff --stat --exit-code plugin/build
